### ISSUE TITLE
Цвета по краям?

### ISSUE THREAD

**Issue by alexpdk** [McFeod/ballistics4fopevm#7]
![_012](https://cloud.githubusercontent.com/assets/8831683/6881842/3b5f6918-d591-11e4-9631-1ba9337dcef2.png)
![_010](https://cloud.githubusercontent.com/assets/8831683/6881843/406b9508-d591-11e4-8809-613eb1f18edc.png)

**Comment by McFeod** [comment]
на жёлтой видно. Само по себе не страшно, конечно, но симптом нехороший. Наверняка, если покрутить туда-сюда sleepFactor, то и что-то похуже можно получить...
![1](https://cloud.githubusercontent.com/assets/8820345/6881864/472abd64-d592-11e4-9fac-6ea77aa75936.png)

**Comment by alexpdk** [comment]
Баг во всей красе. sleepFactor на него, конечно, не влияет. Но если убрать паузу между запусками ...
![_020](https://cloud.githubusercontent.com/assets/8831683/6881932/349c5c2c-d595-11e4-9c71-2cd8901678f5.png)

**Comment by McFeod** [comment]
семафор не спас. Теперь вместо неправильного цвета всё висит
![default](https://cloud.githubusercontent.com/assets/8820345/6885966/f845404c-d646-11e4-8dbf-754b87b08a29.png)
